#!/usr/bin/env bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


PATH="@nix@/bin:@git@/bin:@openssh@/bin:@docker@/bin"


docker load < "$(nix build --no-link --print-out-paths "$1")"
