#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


NAME=$1
TAG=$2

docker tag quyo/${NAME}:dev quyo/${NAME}:${TAG}
docker push quyo/${NAME}:${TAG}
