#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


quyo-runall 'cd /bootstrap.sh && git reset --hard && git pull && git submodule update --init --recursive && git submodule update --recursive --remote && ./fix-permissions'
