#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$' \n\t'


QUYO_HOSTS="\
    fra1-ns \
    fra1-mx \
    fra1-matrix \
    fra1-docker"

for host in ${QUYO_HOSTS}
do
    ssh -t root@do-${host}.tailaccaf.ts.net bash -ilc "'$@'"
    echo -e '\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n\n'
done
