#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


RESTIC_PASSWORD_FILE=${RESTIC_PASSWORD_FILE:-$HOME/.config/restic/passwd}

set +e

while LANG=C IFS=\  read -r REPO KEY; do

  PID=$(pidof restic || true)

  if [ ! -z ${PID} ]; then
    echo "restic is already running, execution cancelled."
    exit 1
  fi

  echo
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "+                                                                                +"
  echo "+   ${KEY:-xxxxxxxx}@${REPO}   +"
  echo "+                                                                                +"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo

  restic --repo "${REPO}" --password-file "${RESTIC_PASSWORD_FILE}" --key-hint=${KEY} "$@"

done <"${RESTIC_MULTIREPOSITORY_FILE:-$HOME/.config/restic/repository}"

set -e
