#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


# create files from template
nix flake new -t github:Samayel/qnixpkgs#node-nest-project .
rm -f package.json.example

# create flake.lock
nix flake metadata >/dev/null

# initialize direnv
direnv allow

# initialize git
git init
git add .


# stage2: install all packages and tools
cat >__stage2 <<EOF
#! /usr/bin/env -S nix shell qnixpkgs#bash qnixpkgs#coreutils qnixpkgs#jq . -i -c bash

npm init -y

npm i -D typescript ts-node @types/node @tsconfig/node18-strictest-esm \
         gulp gulp-typescript del \
         webpack webpack-cli ts-loader html-webpack-plugin \
         style-loader css-loader mini-css-extract-plugin \
         node-sass sass-loader \
         less less-loader \
         husky lint-staged prettier eslint eslint-config-prettier eslint-plugin-prettier @typescript-eslint/eslint-plugin @typescript-eslint/parser \
         nodemon onchange \
         npm-run-all \
         @types/express @types/express-ejs-layouts @types/config @types/jest

npm i express express-ejs-layouts ejs \
      @nestjs/core @nestjs/common @nestjs/platform-express @nestjs/testing rxjs reflect-metadata \
      config properties

function __update_package_json() {
  cat package.json | jq "\$@" >package.json2 ; mv package.json2 package.json
}

__update_package_json '.main = "./src/backend/app.ts"'
__update_package_json '.type = "module"'

__update_package_json '.scripts."prepare" = "husky install"'
__update_package_json '.scripts."pre-commit" = "lint-staged"'
__update_package_json '.scripts."lint" = "eslint src --fix"'
__update_package_json '.scripts."prettify" = "prettier --write src"'
__update_package_json '.scripts."clean" = "gulp clean"'
__update_package_json '.scripts."build_backend" = "gulp backend"'
__update_package_json '.scripts."build_frontend_assets" = "gulp frontend-assets"'
__update_package_json '.scripts."build_frontend_views" = "gulp frontend-views"'
__update_package_json '.scripts."build_frontend_compile:dev" = "webpack --mode development"'
__update_package_json '.scripts."build_frontend_compile:prod" = "webpack --mode production"'
__update_package_json '.scripts."build_frontend:dev" = "run-p build_frontend_assets build_frontend_views build_frontend_compile:dev"'
__update_package_json '.scripts."build_frontend:prod" = "run-p build_frontend_assets build_frontend_views build_frontend_compile:prod"'
__update_package_json '.scripts."build:dev" = "npm run clean && run-p build_backend build_frontend:dev"'
__update_package_json '.scripts."build:prod" = "npm run clean && run-p build_backend build_frontend:prod"'
__update_package_json '.scripts."serve:dev" = "NODE_ENV=development node --experimental-specifier-resolution=node ./dist/backend/app.js"'
__update_package_json '.scripts."serve:prod" = "NODE_ENV=production node --experimental-specifier-resolution=node ./dist/backend/app.js"'
__update_package_json '.scripts."build_serve:dev" = "run-s build:dev serve:dev"'
__update_package_json '.scripts."build_serve:prod" = "run-s build:prod serve:prod"'
__update_package_json '.scripts."watch_backend" = "nodemon --watch config --watch src/backend -e ts,tsx,cts,mts,js,jsx,cjs,mjs,json,properties --exec run-s build_backend serve:dev"'
__update_package_json '.scripts."watch_frontend_assets" = "nodemon --watch src/frontend/static -e svg,webp,gif,jpg,jpeg,png,woff,ttf,otf,webm,avi,mp4,mpg,mpeg,mkv,weba,wav,mp3,aac,ogg,flac,pdf,txt,rtf,doc,docx,xls,xlsx,ppt,pptx,odt,ods,odp,json --exec npm run build_frontend_assets"'
__update_package_json '.scripts."watch_frontend_views" = "nodemon --watch src/frontend/views -e ejs,html,htm --exec npm run build_frontend_views"'
__update_package_json '.scripts."watch_frontend_compile" = "nodemon --watch src/frontend/static -e ts,tsx,cts,mts,js,jsx,cjs,mjs,css,scss,sass,less --exec npm run build_frontend_compile:dev"'
__update_package_json '.scripts."watch_prettier" = "onchange \"**/*\" -- prettier --write --ignore-unknown {{changed}}"'
__update_package_json '.scripts."watch" = "npm run clean && run-p watch_backend watch_frontend_assets watch_frontend_views watch_frontend_compile watch_prettier"'
__update_package_json '.scripts."dev" = "npm run watch"'
__update_package_json '.scripts."prod" = "npm run build_serve:prod"'
EOF

chmod +x __stage2
./__stage2
rm -f __stage2

# stage3: setup husky
cat >__stage3 <<EOF
#! /usr/bin/env -S nix shell . -c bash

npx husky install
npx husky add .husky/pre-commit "npm run pre-commit"
EOF

chmod +x __stage3
./__stage3
rm -f __stage3

# add all files
git add .
