#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


# create files from template
nix flake new -t github:quyo/qnixpkgs#caddy-project .

chmod +x ./cbuild.sh
chmod +x ./ccompose.sh

chmod +x ./flylaunch.sh
chmod +x ./flypush.sh
chmod +x ./flysetup.sh

# create flake.lock
nix flake metadata >/dev/null

# initialize direnv
direnv allow

# initialize git
git init
git add .
