#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


doctl --context quyo.zone compute domain records list --no-header --format Name,Type,ID "$PRJ_QUYO_DOMAIN" | grep -E "^$PRJ_QUYO_SUBDOMAIN +A+ " | awk -F' ' '{print $3}' | xargs --no-run-if-empty doctl --context quyo.zone compute domain records delete --force "$PRJ_QUYO_DOMAIN" && echo "[$PRJ_QUYO_SUBDOMAIN.$PRJ_QUYO_DOMAIN] Existing DNS records deleted." || echo "[$PRJ_QUYO_SUBDOMAIN.$PRJ_QUYO_DOMAIN] No existing DNS records found."

doctl --context quyo.zone compute domain records create --record-type    A --record-name "$PRJ_QUYO_SUBDOMAIN" --record-data "$(flyctl ips list | grep '^v4' | awk -F' ' '{print $2}')" "$PRJ_QUYO_DOMAIN"
doctl --context quyo.zone compute domain records create --record-type AAAA --record-name "$PRJ_QUYO_SUBDOMAIN" --record-data "$(flyctl ips list | grep '^v6' | awk -F' ' '{print $2}')" "$PRJ_QUYO_DOMAIN"

echo
echo If TLS termination is done by Fly.io, run \'flyctl certs add $PRJ_QUYO_SUBDOMAIN.$PRJ_QUYO_DOMAIN --config \"$PWD\"\'.
echo
