#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


PID=$(pidof restic || true)

if [ ! -z ${PID} ]; then
  echo "restic is already running, execution cancelled."
  exit 1
fi

restic backup \
  --repository-file "$HOME/.config/restic/repository.eu" \
  --password-file "$HOME/.config/restic/passwd" \
  --exclude-file "$HOME/.config/restic/exclude.global" \
  --exclude-file "$HOME/.config/restic/exclude.local" \
  --exclude-if-present .duplicity-ignore \
  --exclude-if-present .restic-ignore \
  --cleanup-cache \
  "$@"


PID=$(pidof restic || true)

if [ ! -z ${PID} ]; then
  echo "restic is already running, execution cancelled."
  exit 1
fi

restic backup \
  --repository-file "$HOME/.config/restic/repository.us" \
  --password-file "$HOME/.config/restic/passwd" \
  --exclude-file "$HOME/.config/restic/exclude.global" \
  --exclude-file "$HOME/.config/restic/exclude.local" \
  --exclude-if-present .duplicity-ignore \
  --exclude-if-present .restic-ignore \
  --cleanup-cache \
  "$@"
