#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


cronic restic-backup \
    --tag automatic \
    --tag daily \
    --files-from "$HOME/.config/restic/paths-to-backup.daily.global" \
    --files-from "$HOME/.config/restic/paths-to-backup.daily.local"
