#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


ansible-playbook -i inventory/hosts setup.yml --tags=stop

umount /matrix/synapse/storage/media-store || true
rm -rf /matrix/synapse/storage/media-store || true

ansible-playbook -i inventory/hosts setup.yml --tags=start
