#!/usr/bin/env bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


PATH="@nix@/bin:@git@/bin:@cachix@/bin:@openssh@/bin"


cachix watch-store quyo-public
