#!@bash@/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

@nix@/bin/nix flake archive --json $1 \
  | @jq@/bin/jq -r '.path,(.inputs|to_entries[].value.path)' \
  | @cachix@/bin/cachix push quyo-public
