#!/usr/bin/env bash

set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"

nix flake show --json --legacy $1 \
  | jq '.packages."x86_64-linux"|keys[]' \
  | xargs -I {} $SCRIPTDIR/cachix-push-flake-runtime-closure-single $1#{}
