#!/usr/bin/env bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


PATH="@nix@/bin:@git@/bin:@openssh@/bin:@cachix@/bin"


cachix watch-exec quyo-public "$1" -- "${@:2}"
