#!@bash@/bin/bash

set -e

@nix@/bin/nix flake show --json --legacy $1 \
  | @jq@/bin/jq '.packages."x86_64-linux"|keys[]' \
  | @findutils@/bin/xargs -I {} @out@/bin/cachix-push-flake-runtime-closure-single $1#{}
