#!/usr/bin/env bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


nix flake archive --json "$1" \
  | jq -r '.path,(.inputs|to_entries[].value.path)' \
  | cachix push quyo-public
