#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


if [[ $# -ge 1 ]]; then
  nix develop qnixpkgs#jupyterlab --command generate-directory "$@"
else
  nix develop qnixpkgs#jupyterlab --command generate-directory jupyterlab-drawio jupyterlab-ihaskell
fi
