#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set - euo pipefail
  IFS=$'\n\t'


if [ -z "${FAKENIX:-}" ]; then
FAKENIX="${QNIXPKGS}"
fi


nix-fakechannel \
nix \
--extra-experimental-features nix-command \
--extra-experimental-features flakes \
shell "${FAKENIX}#nix" \
--command "${@}"
