#!/usr/bin/env bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


PATH="@git@/bin:@openssh@/bin:${PATH}"


@out@/bin/nix-fakechannel "$1" @nix@/bin/nix --extra-experimental-features nix-command --extra-experimental-features flakes shell "$2#nix" -c "${@:3}"
