#!@bash@/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


set +e
test "$1" != "-v"
VERBOSE=$?
set -e

if [ $VERBOSE -eq 1 ]; then
  shift
fi


CHANNELDIR=$(mktemp -d)

if [ $VERBOSE -eq 1 ]; then
  @coreutils@/bin/echo -n '{ ... }@args: builtins.trace args '              > $CHANNELDIR/default.nix
else
  @coreutils@/bin/echo -n '{ ... }:'                                        > $CHANNELDIR/default.nix
fi

@coreutils@/bin/echo -n "(builtins.getFlake \"$1\")."                      >> $CHANNELDIR/default.nix
@coreutils@/bin/echo    'outputs.legacyPackages.${builtins.currentSystem}' >> $CHANNELDIR/default.nix

if [ $VERBOSE -eq 1 ]; then
  @coreutils@/bin/cat $CHANNELDIR/default.nix
fi


# inspired by https://ianthehenry.com/posts/how-to-learn-nix/chipping-away-at-flakes/
NIX_PATH="nixpkgs=$CHANNELDIR" ${@:2}


@coreutils@/bin/rm -rf $CHANNELDIR
