#!/usr/bin/env bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


nix-store -q --tree "$(nix-store -qd "$(nix --repeat 0 build --no-link --print-out-paths "$1")")"
