#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


set +e
test "$1" != "-v"
VERBOSE=$?
set -e

if [ $VERBOSE -eq 1 ]; then
  shift
fi


CHANNELDIR=$(mktemp -d)

{
  if [ $VERBOSE -eq 1 ]; then
    echo -n '{ ... }@args: builtins.trace args '
  else
    echo -n '{ ... }:'
  fi

  echo -n "((builtins.getFlake \"$1\")."
  # shellcheck disable=SC2016
  echo -n 'outputs.legacyPackages.${builtins.currentSystem} or {})'
  echo -n " // ((builtins.getFlake \"$1\")."
  # shellcheck disable=SC2016
  echo    'outputs.packages.${builtins.currentSystem} or {})'
} > "$CHANNELDIR/default.nix"

if [ $VERBOSE -eq 1 ]; then
  cat "$CHANNELDIR/default.nix"
fi


# inspired by https://ianthehenry.com/posts/how-to-learn-nix/chipping-away-at-flakes/
NIX_PATH="nixpkgs=$CHANNELDIR" "${@:2}"


rm -rf "$CHANNELDIR"
