#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


if [ -z "${FAKECHANNEL:-}" ]; then
  FAKECHANNEL="${QNIXPKGS}"
fi

if [ -z "${VERBOSE:-}" ]; then
  VERBOSE=0
fi


CHANNELDIR=$(mktemp -d)

{
  if [ ${VERBOSE} -eq 1 ]; then
    echo -n '{ ... }@args: builtins.trace args '
  else
    echo -n '{ ... }:'
  fi

  echo -n "((builtins.getFlake \"${FAKECHANNEL}\")."
  # shellcheck disable=SC2016
  echo -n 'outputs.legacyPackages.${builtins.currentSystem} or {})'
  echo -n " // ((builtins.getFlake \"${FAKECHANNEL}\")."
  # shellcheck disable=SC2016
  echo    'outputs.packages.${builtins.currentSystem} or {})'
} > "${CHANNELDIR}/default.nix"

if [ ${VERBOSE} -eq 1 ]; then
  cat "${CHANNELDIR}/default.nix"
fi


# inspired by https://ianthehenry.com/posts/how-to-learn-nix/chipping-away-at-flakes/
NIX_PATH="nixpkgs=${CHANNELDIR}" "${@}"


rm -rf "${CHANNELDIR}"
