#!/usr/bin/env bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


PATH="@nix@/bin:@git@/bin:@openssh@/bin"


nix copy \
    --to 's3://nix-cache-quyo-net?profile=nix-cache&region=eu-central-1' \
    "$(nix build --no-link --print-out-paths "$1")"
