#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


nix copy \
    --to 's3://nix-cache-quyo-net?profile=nix-cache&region=eu-central-1' \
    "$(nix path-info --json "$1" | jq -r '.[].path')"
