#!@bash@/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

@nix@/bin/nix run nixpkgs#symlinks -- -dr /nix/var/nix/gcroots/ | @gnugrep@/bin/egrep -v ^absolute:

@nix@/bin/nix-collect-garbage -d
