#!/bin/bash

#
# incompatible with dotfiles/.bashrc and dotfiles/.profile
#
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
# set -euo pipefail
# IFS=$'\n\t'


nix profile install qnixpkgs#userprofile

echo 'source "$HOME/.nix-profile/etc/dotfiles/.bashrc"'  >> ~/.bashrc
echo 'source "$HOME/.nix-profile/etc/dotfiles/.profile"' >> ~/.bashrc

source "$HOME/.nix-profile/etc/dotfiles/.bashrc"
source "$HOME/.nix-profile/etc/dotfiles/.profile"

nix profile install --priority 2 ~/.config/nix/userprofile-local/
