#!@bash@/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

@nix@/bin/nix copy \
    --to 's3://nix-cache-quyo-net?profile=nix-cache&region=eu-central-1' \
    $(@nix@/bin/nix build --no-link --print-out-paths $1)
