#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


nix profile wipe-history

symlinks -dr /nix/var/nix/gcroots/ | grep -E -v ^absolute:

nix-collect-garbage -d
