#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


nix-fakechannel "$1" nix --extra-experimental-features nix-command --extra-experimental-features flakes shell "$2#nix" -c "${@:3}"
