#!@bash@/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

@nix@/bin/nix-store -q --tree $(@nix@/bin/nix-store -qd $(@nix@/bin/nix build --no-link --print-out-paths $1))
