name: nixbuild-ci

on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-flake:
    name: Build flake
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v18
    secrets:
      nixbuild_ssh_key: ${{ secrets.NIXBUILD_SSH_KEY }}
    with:
      nix_conf: |
        sandbox = relaxed
      filter_builds: '.top_attr == "packages" and .system == "x86_64-linux"'
#     filter_builds: '.attr == "ci-build"'

  upload-image:
    name: Upload image
    runs-on: ubuntu-22.04
    needs: build-flake
    steps:
      - uses: actions/checkout@v3

      - uses: nixbuild/nix-quick-install-action@v23
        with:
          nix_on_tmpfs: false
          nix_conf: |
            experimental-features = nix-command flakes
            sandbox = relaxed

      - uses: nixbuild/nixbuild-action@v18
        with:
          nixbuild_ssh_key: ${{ secrets.NIXBUILD_SSH_KEY }}

      - name: Fix nix.conf
        working-directory: .
        run: |
          NIX_BUILDERS_FILE="$(mktemp)"
          cat >"$NIX_BUILDERS_FILE" <<EOF
          eu.nixbuild.net x86_64-linux - 100 1 big-parallel,benchmark
          eu.nixbuild.net i686-linux - 100 1 big-parallel,benchmark
          eu.nixbuild.net aarch64-linux - 100 1 big-parallel,benchmark
          eu.nixbuild.net armv7l-linux - 100 1 big-parallel,benchmark
          EOF

          NIX_CONF_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/nix/nix.conf"
          echo "builders = @$NIX_BUILDERS_FILE" >>"$NIX_CONF_FILE"
          cat "$NIX_CONF_FILE"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to git.quyo.net
        uses: docker/login-action@v2
        with:
          registry: git.quyo.net
          username: ${{ secrets.GIT_QUYO_NET_USERNAME }}
          password: ${{ secrets.GIT_QUYO_NET_ACCESS_TOKEN }}

      - name: Load and push docker image (shellscripts.nix:latest)
        working-directory: .
        run: |
          nix build .#docker
          nix run github:quyo/shellscripts.nix#docker-load-nix-build .#docker
          docker push quyo/shellscripts.nix:latest
          docker tag quyo/shellscripts.nix:latest git.quyo.net/quyo/shellscripts.nix:latest
          docker push git.quyo.net/quyo/shellscripts.nix:latest
